config/routes.rb
Rails.application.routes.draw do
  resource :users, only: [:edit] do
    member do
      get ':id/edit_password', to: 'users#edit_password', as: 'edit_password'
      patch ':id/update_password', to: 'users#update_password', as: 'update_password'
    end
  end
  resources :admin
  resources :searches
  resources :announcements
  resources :videos do
    resources :comments
  end
  resources :majors
  resources :faculties
  resources :documents do
    member do
      get :approve
    end
  end
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :posts do
    resources :comments
    member do
      patch 'upvote', to: 'posts#upvote'
      patch 'downvote', to: 'posts#downvote'
    end
  end
  resources :courses do
    member do
      get 'posts', to: 'courses#posts'
      get 'documents', to: 'courses#documents'
      get 'videos', to: 'courses#videos'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
  }
  devise_scope :user do
    match 'users/:id', to: 'users#destroy', via: :delete, as: :admin_delete_user
    get 'users/:username', to: 'users/sessions#profile', as: 'user_profile'
    get 'users/:id/edit', to: 'users/registrations#edit', as: 'edit_user_profile'
    get 'users', to: 'users/registrations#index', as: 'users'
    get 'login', to: 'users/sessions#new', as: 'login'
    get 'register', to: 'users/registrations#new', as: 'register'
  end
  authenticated :user do
    root to: "posts#index"
  end

  root to: "static_pages#index"
end

app/models/announcement.rb
class Announcement < ApplicationRecord
  include ImageUploader[:image]
  validates :title, :content, :image, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  validates :content, presence: true
  validates :content, length: {maximum: 65535}

end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :major
  belongs_to :user
  has_many :documents, :dependent => :delete_all
  has_many :posts, :dependent => :delete_all
  validates :name, :major_id, presence: true
  validates :name, length: {maximum: 50}

  include ImageUploader[:image]

end

app/models/document.rb
class Document < ApplicationRecord
  include DocumentUploader[:document]
  belongs_to :course
  belongs_to :user
  validates :title, :document, :course_id, presence: true
  scope :approved_document, -> { where(approved: true) }

  def self.search(search)
    documents = Document.approved_document.where("title LIKE ?", "%#{search}%") if search.present?
  end
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :majors, :dependent => :delete_all
  belongs_to :user
  validates :name, presence: true
  validates :name, length: {maximum: 100}
end

app/models/major.rb
class Major < ApplicationRecord
  belongs_to :faculty
  belongs_to :user
  has_many :courses, :dependent => :delete_all
  validates :name, :faculty_id, presence: true
  validates :name, length: {maximum: 50}

end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :actor, class_name: "User"
  belongs_to :notifiable, polymorphic: true
  scope :unread, -> { where(read_at: nil) }
  
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable
  belongs_to :user
  belongs_to :course
  has_many :comments, as: :commentable, :dependent => :delete_all
  has_many :users, through: :comments
  validates :title, :content, :course_id, presence: true
  def post_votes
    self.get_upvotes.size - self.get_downvotes.size
  end
  def self.search(search)
    posts = Post.where("title LIKE ?", "%#{search}%") if search.present?
  end
  def self.top_courses
    sorted_courses = Hash.new
    @courses = Course.all.each do |course|
      sorted_courses[course] = course.posts.count
    end
    sorted_courses.sort_by {|_key, value| value}.take(10).reverse
  end
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :docments, :dependent => :delete_all
  has_many :posts, :dependent => :delete_all
  has_many :videos, :dependent => :delete_all
  has_many :comments, :dependent => :delete_all
  has_many :Notifications, foreign_key: :recipient_id, :dependent => :delete_all
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable,
         :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook, :google_oauth2]

  validates :username, uniqueness: { case_sensitive: false }
  validates :bio, length: { maximum: 255 }
  validates :first_name, :last_name, :username, length: { maximum: 20 }
  validates :email, length: { maximum: 50 }
  validates :username, :format => { :with => /\A[a-zA-Z0-9]*\z/,
    :message => "can only contain letters and numbers" }

  include ImageUploader[:image]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.bio = auth.info.about
      user.username = auth.info.first_name + auth.info.last_name
      user.email = auth.info.email
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.skip_confirmation!
    end
  end

  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"]) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_many :comments, as: :commentable

  validates :title, :youtube_video_id, :course_id, :status, presence: true
  def self.search(search)
    videos = Video.where("title LIKE ?", "%#{search}%") if search.present?
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    if params[:search] and not params[:search].empty?
      @documents = Document.search(params[:search]).order("created_at DESC").paginate(page: params[:page], per_page: 12)
    else
      @documents = Document.approved_document.order(created_at: :desc).paginate(page: params[:page], per_page: 12)
    end
  end

  def show
    redirect_to :documents
  end

  def new
    @document = Document.new
  end

  def edit
  end

  def create
    @document = Document.new(document_params)
    @document.user = current_user
    @document.approved = true if current_user.is_admin
    if @document.save
      redirect_to :documents, notice: "Document was successfully created, It will show when it's approved."
    else
      render :new
    end
  end

  def update
    if @document.update(document_params)
      redirect_to "/admin"
    else
      render :edit
    end
  end

  def destroy
    @document.destroy
    redirect_to "/admin"
  end

  def approve
  end
  private
    def set_document
      @document = Document.find(params[:id])
    end
    def document_params
      params.require(:document).permit(:title, :document, :course_id, :approved)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" unless devise_error_messages?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    !resource.errors.empty?
  end

end

app/helpers/documents_helper.rb
module DocumentsHelper
  def extension_type(mime_type)
    Rack::Mime::MIME_TYPES.invert[mime_type].sub(/./, '').upcase
  end
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/majors_helper.rb
module MajorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/documents/_form.html.erb
<%= form_for(document) do |f| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= f.collection_select :course_id, Course.all, :id, :name, prompt: "Course name:" %>
    <%= f.text_field :title, placeholder: "Title describe the document" %>
  <label for="avatar_upload" id="avatar_label">
    <svg class="icon-add-document"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-add-document"></use></svg>
    <span>Select a document to upload</span>
  </label>
  <%= f.hidden_field :document, value: f.object.cached_document_data %>
  <%= f.file_field :document, id: "avatar_upload", accept: ".pdf, .doc, .docx, .ppt, .pptx" %>
  <%= f.submit "Publish!", class: "btn document-submit" %>
<% end %>

app/views/documents/edit.html.erb
<div class="container document-form">
  <%= render 'form', document: @document %>
  <div class="document-inst">
    <h1>Editing Document</h1>
    <ul>
      <li>Upload your documents in PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX, TXT and TEXT types.</li>
      <li>Write a meaningful title that describe your document.</li>
      <li>The Document you will upload it will be review and will appear after approved.</li>
    </ul>
  </div>
</div>

app/views/documents/index.html.erb
<div class="documents-functions container flex-start">
  <%= form_tag documents_path, method: :get, class: "documents-search search-form" do %>
    <%= text_field_tag :search, params[:search], placeholder: "search in documents", class: "search-field" %>
    <%= button_tag type: "submit", class: "search-btn" do %>
      <svg class="icon-search"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-search"></use></svg>
    <% end %>
  <% end %>
  <%= link_to new_document_path, class: "add-new-document add-new-btn" do %>
    Add Document
  <% end %>
</div>

  <div class="documents">
    <% @documents.each do |document| %>
      <div class="document white-box">
        <div class="extension-type">

          <div class="title">
            <%= document.title %>
          </div>
        </div>
        <div class="document-info flex-column">
          <div class="username info-element">
            <%= image_tag (document.user.image_url or avatar_for_gender(document.user)), width: "20px", height: "20px", class: "user_avatar" %>
            <%= link_to document.user.username, user_profile_path(document.user.username) %>
          </div>
          <div class="time-ago info-element">
            <svg class="icon-time sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-time"></use></svg>
            <%= time_ago_in_words(document.created_at) %>
          </div>
          <%= link_to course_path(document.course), class: "course info-element" do %>
          <svg class="icon-apps sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-apps"></use></svg>
          <%= truncate(document.course.name, length: 25) %>
          <% end %>
          <div class="info-element">
            <% if current_user.try(:is_admin) %>
              <%= link_to "delete", document, method: :delete, data: { confirm:  "Are you sure?"} %>
            <% end %>
          </div>

        </div>
        <%= link_to document.document_url, class: "download-btn" do %>
        Download
        <% end %>
      </div>
    <% end %>
  </div>
  <br>
  <%= will_paginate @documents %>

app/views/documents/new.html.erb
<div class="container document-form">
  <%= render 'form', document: @document %>
  <div class="document-inst">
    <h1>New Document</h1>
    <ul>
      <li>Upload your documents in PDF, DOC, DOCX, PPT, PPTX, XLS, XLSX, TXT and TEXT types.</li>
      <li>Write a meaningful title that describe your document.</li>
      <li>The Document you will upload it will be review and will appear after approved.</li>
    </ul>
  </div>
</div>