config/routes.rb
Rails.application.routes.draw do
  resource :users, only: [:edit] do
    member do
      get ':id/edit_password', to: 'users#edit_password', as: 'edit_password'
      patch ':id/update_password', to: 'users#update_password', as: 'update_password'
    end
  end
  resources :admin
  resources :searches
  resources :announcements
  resources :videos do
    resources :comments
  end
  resources :majors
  resources :faculties
  resources :documents do
    member do
      get :approve
    end
  end
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end
  resources :posts do
    resources :comments
    member do
      patch 'upvote', to: 'posts#upvote'
      patch 'downvote', to: 'posts#downvote'
    end
  end
  resources :courses do
    member do
      get 'posts', to: 'courses#posts'
      get 'documents', to: 'courses#documents'
      get 'videos', to: 'courses#videos'
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    passwords: 'users/passwords',
    confirmations: 'users/confirmations',
  }
  devise_scope :user do
    match 'users/:id', to: 'users#destroy', via: :delete, as: :admin_delete_user
    get 'users/:username', to: 'users/sessions#profile', as: 'user_profile'
    get 'users/:id/edit', to: 'users/registrations#edit', as: 'edit_user_profile'
    get 'users', to: 'users/registrations#index', as: 'users'
    get 'login', to: 'users/sessions#new', as: 'login'
    get 'register', to: 'users/registrations#new', as: 'register'
  end
  authenticated :user do
    root to: "posts#index"
  end

  root to: "static_pages#index"
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authenticate_admin, except: [:index, :show]

  def index
    if params[:major_id] && params[:major_id].present?
      @courses = Course.where(major_id: params[:major_id]).order(:name)
      @major = Major.find(params[:major_id])
    else
      @courses = Course.where(major_id: 1).order(:name)
      @major = Major.find(1)
    end
  end

  def show
    @posts = Post.where(course_id: @course.id).paginate(page: params[:page], per_page: 10)
    @documents = Document.where(course_id: @course.id).paginate(page: params[:page], per_page: 10)
    @videos = Video.where(course_id: @course.id).paginate(page: params[:page], per_page: 10)
  end

  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)
    if @course.save
    redirect_to @course, notice: 'Course was successfully created.'
    else
    render :new, alert: 'Something went wrong!'
    end
  end

  def update
    if @course.update(course_params)
      redirect_to @course, success: 'Course was successfully updated.'
    else
      render :edit, alert: 'Something went wrong!'
    end
  end

  def destroy
    @course.destroy
    redirect_to courses_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:name, :major_id, :image)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <%= f.text_field :name, placeholder: "course name" %><br>
    <%= f.grouped_collection_select :major_id, Faculty.all, :majors, :name, :id, :name, prompt: "major name:" %>
    <div class="user-avatar">
      <label for="avatar_upload" class="btn btn-block" id="avatar_label">
        <svg class="icon-image"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-image"></use></svg>
        <span>Select a picture</span>
      </label>
      <%= f.hidden_field :image, value: f.object.cached_image_data %>
      <%= f.file_field :image, id: "avatar_upload", accept: ".png, .jpeg, .jpg" %>
    </div>
    <%= f.submit "Add", class: "btn" %>
<% end %>

app/views/courses/edit.html.erb
<div class="white-box new-course">
  <h1>Editing Course</h1>
  <%= render 'form', course: @course %>
</div>

app/views/courses/index.html.erb
<div class="container">

  <%= form_tag courses_path, method: :get, id: "select_major" do %>
    <%= grouped_collection_select(nil, :major_id, Faculty.all, :majors, :name, :id, :name, prompt: "Select a major:") %>
  <% end %>
  <div class="line"></div>
  <div class="major-name">
    <%= @major.name %>
  </div>
  <div class="courses">
    <% @courses.each do |course| %>
        <%= link_to course_path(course), class: "course-show white-box" do %>
          <div class="name">
            <%= course.name %>
          </div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/courses/new.html.erb
<div class="white-box new-course">
  <h1>New Course</h1>
  <%= render 'form', course: @course %>
</div>

app/views/courses/show.html.erb
<div class="container">
  <div class="white-box course-name">
    <%= @course.name %>
  </div>
	<ul class="tabs">
		<li class="tab-link current" data-tab="tab-1">Discussions</li>
		<li class="tab-link" data-tab="tab-2">Documents</li>
		<li class="tab-link" data-tab="tab-3">Videos</li>
	</ul>

	<div id="tab-1" class="tab-content current">
    <div class="posts flex-column">
      <% if @posts.size > 0 %>
        <% @posts.each do |post| %>
          <div class="white-box post">
            <div class="title">
              <%= link_to post.title, post_path(post) %>
            </div>
            <div class="info flex-center-start">
              <div class="votes flex-center-around">
                <%= link_to upvote_post_path(post), method: :patch, remote: true, class: "upvote vote-box" do %>
                <svg class="icon-chevron-down upvote-icon sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-chevron-down"></use></svg>
                <% end %>
                <div id="vote_avg_<%= post.id %>" class="vote-avg vote-box">
                  <%= post.post_votes %>
                </div>
                <%= link_to downvote_post_path(post), method: :patch, remote: true, class: "downvote vote-box" do %>
                <svg class="icon-chevron-down sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-chevron-down"></use></svg>
                <% end %>
              </div>
              <div class="username info-element">
                <%= image_tag (post.user.image_url or asset_path 'default-avatar.png'), width: "20px", height: "20px", class: "user_avatar" %>
                <%= link_to post.user.username, user_profile_path(post.user.username) %>
              </div>
              <div class="time-ago info-element">
                <svg class="icon-time sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-time"></use></svg>
                <%= time_ago_in_words(post.created_at) %>
              </div>
              <div class="category info-element">
                <svg class="icon-apps sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-apps"></use></svg>
                <%= truncate(post.course.name, length: 32) %>
              </div>
              <div class="comments info-element">
                <svg class="icon-chat sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-chat"></use></svg>
                <%= post.comments.count %>
              </div>
            </div>
          </div>
        <% end %>
      <% else %>
      <div class="no-results">
        There is no discussions!
      </div>
      <% end %>
    </div>
    <%= will_paginate @posts %>
	</div>

  <div id="tab-2" class="tab-content">
    <div class="documents">
      <% if @documents.length > 0 %>
        <div class="documents">
          <% @documents.each do |document| %>
          <div class="document white-box">
            <div class="extension-type">

              <div class="title">
                <%= document.title %>
              </div>
              <%# extension_type(document.document.mime_type) %>
            </div>
            <div class="document-info flex-column">
              <div class="username info-element">
                <%= image_tag (document.user.image_url or avatar_for_gender(document.user)), width: "20px", height: "20px", class: "user_avatar" %>
                <%= link_to document.user.username, user_profile_path(document.user.username) %>
              </div>
              <div class="time-ago info-element">
                <svg class="icon-time sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-time"></use></svg>
                <%= time_ago_in_words(document.created_at) %>
              </div>
              <%= link_to course_path(document.course), class: "course info-element" do %>
              <svg class="icon-apps sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-apps"></use></svg>
              <%= truncate(document.course.name, length: 25) %>
              <% end %>
            </div>
            <%= link_to document.document_url, class: "download-btn" do %>
            Download
            <% end %>
          </div>
          <% end %>
        </div>
      <% else %>
      <div class="no-results">
        There is no documents!
      </div>
      <% end %>
    </div>
    <%= will_paginate @documents %>
	</div>


	<div id="tab-3" class="tab-content">
    <div class="videos container">
      <% if @videos.size > 0 %>
        <div class="videos container">
          <% @videos.each do |video| %>
            <div class="video" style="background-image:url(https://i1.ytimg.com/vi/<%= video.youtube_video_id %>/0.jpg)">
              <%= link_to video_path(video), class: "title" do %>
                <%= video.title %>
              <% end %>
              <div class="status">
                <%= video.status %>
              </div>
              <div class="time">
                <svg class="icon-calendar sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-calendar"></use></svg>
                <%= video.created_at.strftime("%b %d, %Y") %>
              </div>
              <%= link_to course_path(video.course), class: "course" do %>
                <svg class="icon-apps sixteenth-px"><use xlink:href="<%= asset_path 'icons.svg' %>#icon-apps"></use></svg>
                <%= truncate(video.course.name, length: 32) %>
              <% end %>
            </div>
          <% end %>
        </div>

      <% else %>
        <div class="no-results">
          There is no videos!
        </div>
      <% end %>
    </div>
    <%= will_paginate @videos %>
	</div>

</div><!-- container -->